name: my24app
description: My24Service app.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.37.2+261

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  bloc_concurrency: ^0.2.0
  cached_network_image: ^3.2.1
  decimal: ^2.2.0
  easy_localization: ^3.0.1
  equatable: ^2.0.0
  file_picker: '>=5.2.10'
  firebase_messaging: ^14.4.1
  flutter_bloc: ^8.0.1
  flutter_datetime_picker: ^1.5.0
  flutter_plugin_android_lifecycle: ^2.0.4
  flutter_map: ^5.0.0
  flutter_rating_bar: ^4.0.1
  flutter_signature_pad: ^3.0.0
  flutter_typeahead: ^4.0.0
  image: ^3.2.0
  flutter_multi_formatter: ^2.11.5
  image_picker: ^0.8.5+3
  intl: ^0.18.0
  modal_progress_hud_nsn: ^0.4.0
  shared_preferences: ^2.1.0
  flutter_sticky_header: ^0.6.5
  #  table_sticky_headers: ^2.0.5
  table_sticky_headers:
    git:
      url: https://github.com/pengboboer/sticky-headers-table.git
  #  sliver_tools: ^0.2.10
  upgrader: ^9.0.0
  # stream
  #  stream_chat_flutter: ^5.3.0
  streaming_shared_preferences: ^2.0.0
  logging: ^1.2.0
  barcode_scan2: ^4.3.0
  uni_links: ^0.5.1
  sentry_flutter: ^7.16.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  my24_flutter_core:
#    path: ../my24_flutter_core
    git:
      url: https://github.com/My24Service/my24_flutter_core.git

  my24_flutter_equipment:
#    path: ../my24_flutter_equipment
    git:
      url: https://github.com/My24Service/my24_flutter_equipment.git

  my24_flutter_member_models:
    #    path: ../my24_flutter_member_models
    git:
      url: https://github.com/My24Service/my24_flutter_member_models.git

  my24_flutter_orders:
#            path: ../my24_flutter_orders
    git:
      url: https://github.com/My24Service/my24_flutter_orders.git
      ref: develop

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  flutter_branch_sdk: ^7.0.2

dependency_overrides:
  package_info_plus: ^4.0.1
  wakelock_windows: any
  win32: any

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  mockito: ^5.2.0
  build_runner: ^2.1.11
  network_image_mock: ^2.0.1
  flutter_test:
    sdk: flutter

flutter_icons:
  android: 'launcher_icon'
  ios: false
  image_path: 'assets/icon/icon.png'

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # Our translation resources
  assets:
    - assets/bg1.jpg
    - assets/bg2.jpg
    - assets/bg3.jpg
    - assets/bg4.jpg
    - assets/icon/icon.png
    - assets/
    - assets/langs/
    - resources/langs/

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
