version: '2.1'

jobs:
  build:
    working_directory: ~/circleci-my24app
    docker:
      - image: cimg/base:2021.04
        environment:
          TESTING: 1
    steps:
      - checkout
      - run:
          name: install flutter
          command: |
            git clone https://github.com/flutter/flutter.git
      - run:
          name: run tests
          command: |
              ./flutter/bin/flutter test
