version: 2

jobs:
  build:
    docker:
      - image: cimg/python:3.8.10
        environment:
          TESTING: 1
    steps:
      - checkout
      - run:
          name: clone repo
          command: git clone https://github.com/flutter/flutter.git
      - run:
          name: pub get
          command: ./flutter/bin/flutter pub get
      - run:
          name: run tests
          command: ./flutter/bin/flutter test

#
#jobs:
#  test:
#    working_directory: ~/circleci-my24app
#    docker:
#      - image: cimg/base:2021.04
#        environment:
#          TESTING: 1
#    steps:
#      - checkout
#      - run:
#          name: install flutter
#          command: |
#            git clone https://github.com/flutter/flutter.git
#      - run:
#          name: run tests
#          command: |
#            ./flutter/bin/flutter test
