version: '2.1'

orbs:
  flutter: circleci/flutter@1.0.1
  environment:
    TESTING: 1

jobs:
  test:
    executor:
      name: android/android-machine
    steps:
      - flutter/install_sdk_and_pub:
          version: 2.2.3
      - run:
        name: upgrade flutter
        command: |
          flutter upgrade

#
#jobs:
#  test:
#    working_directory: ~/circleci-my24app
#    docker:
#      - image: cimg/base:2021.04
#        environment:
#          TESTING: 1
#    steps:
#      - checkout
#      - run:
#          name: install flutter
#          command: |
#            git clone https://github.com/flutter/flutter.git
#      - run:
#          name: run tests
#          command: |
#            ./flutter/bin/flutter test
