version: '2.1'

jobs:
  build:
    working_directory: ~/circleci-my24app
    docker:
      - image: cimg/base:2021.04
        environment:
          TESTING: 1
    steps:
      - checkout
      - run:
          - git clone https://github.com/flutter/flutter.git
          - ./flutter/bin/flutter test
